import { describe, it, expect } from "vitest";
import fixture from "./__generated__/contract-fixture.json";
import type {
  AppSettings,
  Concept,
  DailySession,
  GamificationState,
  IpcResult,
  Question,
  QuizResult,
} from "./contract";

// The fixture is generated by the Rust test `writes_contract_fixture`
// (run `cargo test` first). Each sample below is assigned to its TS interface:
// if Rust's camelCase JSON shape diverged from the TS contract, the property
// access assertions would read `undefined` and fail (blocklist #12). This is
// the FE side of the round-trip; the BE side lives in src-tauri/src/lib.rs.

const f = fixture as Record<string, unknown>;

describe("FE/BE contract round-trip", () => {
  it("GamificationState matches", () => {
    const g = f.gamificationState as GamificationState;
    expect(typeof g.xp).toBe("number");
    expect(typeof g.level.level).toBe("number");
    expect(typeof g.level.title).toBe("string");
    expect(typeof g.level.xpIntoLevel).toBe("number");
    expect(typeof g.level.xpForNextLevel).toBe("number");
    expect(typeof g.streak.currentStreak).toBe("number");
    expect(typeof g.streak.longestStreak).toBe("number");
    expect(typeof g.streak.freezesAvailable).toBe("number");
    expect(typeof g.streak.lastActiveDate).toBe("string");
    expect(Array.isArray(g.recentXpEvents)).toBe(true);
    expect(typeof g.recentXpEvents[0]?.amount).toBe("number");
    expect(typeof g.recentXpEvents[0]?.source).toBe("string");
    expect(typeof g.recentXpEvents[0]?.description).toBe("string");
    expect(typeof g.recentXpEvents[0]?.createdAt).toBe("string");
    expect(Array.isArray(g.badges)).toBe(true);
    expect(typeof g.badges[0]?.iconName).toBe("string");
    // earnedAt may be string | null
    expect(["string", "object"]).toContain(typeof g.badges[0]?.earnedAt);
  });

  it("Concept matches (incl. effectiveMastery + state)", () => {
    const c = f.concept as Concept;
    expect(typeof c.id).toBe("string");
    expect(typeof c.domain).toBe("string");
    expect(typeof c.module).toBe("string");
    expect(typeof c.title).toBe("string");
    expect(Array.isArray(c.prerequisites)).toBe(true);
    expect(Array.isArray(c.learningObjectives)).toBe(true);
    expect(typeof c.difficultyTier).toBe("number");
    expect(Array.isArray(c.errorPatterns)).toBe(true);
    expect(typeof c.masteryScore).toBe("number");
    expect(typeof c.effectiveMastery).toBe("number");
    expect(typeof c.easeFactor).toBe("number");
    expect(typeof c.intervalDays).toBe("number");
    expect(["string", "object"]).toContain(typeof c.nextReview);
    expect(["completed", "in_progress", "unlocked", "locked"]).toContain(
      c.state,
    );
  });

  it("Question matches the locked quiz schema", () => {
    const q = f.question as Question;
    expect(typeof q.id).toBe("string");
    expect(["multiple_choice", "fill_in_blank", "free_response"]).toContain(
      q.type,
    );
    expect(typeof q.prompt).toBe("string");
    expect(typeof q.explanation).toBe("string");
    expect(typeof q.difficulty).toBe("number");
    expect(typeof q.isTransfer).toBe("boolean");
    // multiple_choice carries options[].isCorrect
    expect(Array.isArray(q.options)).toBe(true);
    expect(typeof q.options?.[0]?.isCorrect).toBe("boolean");
  });

  it("QuizResult includes finalScore (catches bug 0e)", () => {
    const r = f.quizResult as QuizResult;
    expect(typeof r.conceptId).toBe("string");
    expect(Array.isArray(r.answers)).toBe(true);
    expect(typeof r.answers[0]?.questionId).toBe("string");
    expect(typeof r.answers[0]?.isCorrect).toBe("boolean");
    expect(typeof r.answers[0]?.score).toBe("number");
    expect(["string", "object"]).toContain(
      typeof r.answers[0]?.errorPatternDetected,
    );
    expect(typeof r.finalScore).toBe("number");
  });

  it("DailySession populates interleavedSet", () => {
    const s = f.dailySession as DailySession;
    expect(Array.isArray(s.conceptsNew)).toBe(true);
    expect(Array.isArray(s.conceptsReview)).toBe(true);
    expect(Array.isArray(s.interleavedSet)).toBe(true);
    expect(s.interleavedSet.length).toBeGreaterThan(0);
    expect(typeof s.estimatedMinutes).toBe("number");
  });

  it("AppSettings matches", () => {
    const a = f.appSettings as AppSettings;
    expect([15, 30, 45, 60]).toContain(a.dailyGoalMinutes);
    expect(["light", "dark", "system"]).toContain(a.theme);
    expect(typeof a.baseModel).toBe("string");
    expect(typeof a.reasoningModel).toBe("string");
    expect(typeof a.newConceptsPerSession).toBe("number");
    expect(typeof a.notificationsEnabled).toBe("boolean");
    expect(typeof a.apiKeyPresent).toBe("boolean");
  });

  it("IpcResult uses a boolean ok discriminant", () => {
    const ok = f.ipcOk as IpcResult<AppSettings>;
    expect(ok.ok).toBe(true);
    if (ok.ok) {
      expect(typeof ok.data.baseModel).toBe("string");
    }
    const err = f.ipcErr as IpcResult<AppSettings>;
    expect(err.ok).toBe(false);
    if (!err.ok) {
      expect(typeof err.error).toBe("string");
    }
  });
});
