import { describe, it, expect } from "vitest";
import fixture from "./__generated__/contract-fixture.json";
import type {
  AnswerSubmission,
  AppSettings,
  Concept,
  DailyProgress,
  DailySession,
  GamificationState,
  PlacementResult,
  QuizOutcome,
  QuizPayload,
  WireQuestion,
} from "./contract";

// The fixture is generated by the Rust test `writes_contract_fixture`
// (run `cargo test` first). Each sample below is assigned to its TS interface:
// if Rust's camelCase JSON shape diverged from the TS contract, the property
// access assertions would read `undefined` and fail (blocklist #12). This is
// the FE side of the round-trip; the BE side lives in src-tauri/src/lib.rs.
//
// Note: there is no fixture entry for an IPC envelope — `IpcResult<T>` is
// synthesized CLIENT-side in src/lib/ipc.ts (see contract.ts), so there is no
// Rust shape to round-trip.

const f = fixture as Record<string, unknown>;

describe("FE/BE contract round-trip", () => {
  it("GamificationState matches", () => {
    const g = f.gamificationState as GamificationState;
    expect(typeof g.xp).toBe("number");
    expect(typeof g.level.level).toBe("number");
    expect(typeof g.level.title).toBe("string");
    expect(typeof g.level.xpIntoLevel).toBe("number");
    expect(typeof g.level.xpForNextLevel).toBe("number");
    expect(typeof g.streak.currentStreak).toBe("number");
    expect(typeof g.streak.longestStreak).toBe("number");
    expect(typeof g.streak.freezesAvailable).toBe("number");
    expect(typeof g.streak.lastActiveDate).toBe("string");
    expect(Array.isArray(g.recentXpEvents)).toBe(true);
    expect(typeof g.recentXpEvents[0]?.amount).toBe("number");
    expect(typeof g.recentXpEvents[0]?.source).toBe("string");
    expect(typeof g.recentXpEvents[0]?.description).toBe("string");
    expect(typeof g.recentXpEvents[0]?.createdAt).toBe("string");
    expect(Array.isArray(g.badges)).toBe(true);
    expect(typeof g.badges[0]?.iconName).toBe("string");
    // earnedAt may be string | null
    expect(["string", "object"]).toContain(typeof g.badges[0]?.earnedAt);
  });

  it("Concept matches (incl. effectiveMastery, lastAttemptAt + state)", () => {
    const c = f.concept as Concept;
    expect(typeof c.id).toBe("string");
    expect(typeof c.domain).toBe("string");
    expect(typeof c.module).toBe("string");
    expect(typeof c.title).toBe("string");
    expect(Array.isArray(c.prerequisites)).toBe(true);
    expect(Array.isArray(c.learningObjectives)).toBe(true);
    expect(typeof c.difficultyTier).toBe("number");
    expect(Array.isArray(c.errorPatterns)).toBe(true);
    expect(typeof c.masteryScore).toBe("number");
    expect(typeof c.effectiveMastery).toBe("number");
    expect(typeof c.easeFactor).toBe("number");
    expect(typeof c.intervalDays).toBe("number");
    expect(["string", "object"]).toContain(typeof c.nextReview);
    // string | null; the sample carries a real timestamp so a missing field
    // (undefined) fails here.
    expect(typeof c.lastAttemptAt).toBe("string");
    expect(["completed", "in_progress", "unlocked", "locked"]).toContain(
      c.state,
    );
  });

  it("WireQuestion is REDACTED: renderable fields only, NO answer key (H10)", () => {
    const q = f.wireQuestion as WireQuestion;
    expect(typeof q.id).toBe("string");
    expect(["multiple_choice", "fill_in_blank", "free_response"]).toContain(
      q.type,
    );
    expect(typeof q.prompt).toBe("string");
    expect(typeof q.isTransfer).toBe("boolean");
    expect(Array.isArray(q.options)).toBe(true);
    expect(typeof q.options?.[0]?.id).toBe("string");
    expect(typeof q.options?.[0]?.text).toBe("string");

    // The answer key must NOT exist anywhere in the wire payload.
    const raw = JSON.stringify(f.wireQuestion);
    for (const leaked of ["isCorrect", "blanks", "rubric", "explanation"]) {
      expect(raw).not.toContain(leaked);
    }
  });

  it("QuizPayload binds redacted questions to a quiz-instance nonce", () => {
    const p = f.quizPayload as QuizPayload;
    expect(typeof p.quizId).toBe("string");
    expect(p.quizId.length).toBeGreaterThan(0);
    expect(Array.isArray(p.questions)).toBe(true);
    expect(typeof p.questions[0]?.id).toBe("string");
    expect(typeof p.questions[0]?.prompt).toBe("string");
    // The wrapped questions are the same REDACTED wire shape (H10).
    const raw = JSON.stringify(f.quizPayload);
    for (const leaked of ["isCorrect", "blanks", "rubric", "explanation"]) {
      expect(raw).not.toContain(leaked);
    }
  });

  it("AnswerSubmission folds latency per-answer", () => {
    const a = f.answerSubmission as AnswerSubmission;
    expect(typeof a.questionId).toBe("string");
    expect(typeof a.answer).toBe("string");
    expect(typeof a.latencyMs).toBe("number"); // number | null; sample is set
  });

  it("QuizOutcome carries graded review data + persist status", () => {
    const o = f.quizOutcome as QuizOutcome;
    expect(Array.isArray(o.perQuestion)).toBe(true);
    expect(o.perQuestion.length).toBeGreaterThanOrEqual(3);
    for (const g of o.perQuestion) {
      expect(typeof g.questionId).toBe("string");
      expect(typeof g.userAnswer).toBe("string");
      expect(typeof g.isCorrect).toBe("boolean");
      expect(typeof g.score).toBe("number");
      expect(["string", "object"]).toContain(typeof g.errorPatternDetected);
      expect(["string", "object"]).toContain(typeof g.correctAnswer);
      expect(["string", "object"]).toContain(typeof g.feedback);
    }
    // The sample is realistic: correctAnswer populated for objective types,
    // null for free_response; feedback populated.
    expect(typeof o.perQuestion[0]?.correctAnswer).toBe("string");
    expect(o.perQuestion[2]?.correctAnswer).toBeNull();
    expect(typeof o.perQuestion[2]?.feedback).toBe("string");

    expect(typeof o.finalScore).toBe("number");
    expect(typeof o.allCorrect).toBe("boolean");
    expect(typeof o.recorded).toBe("boolean");
    // retryToken is null exactly when recorded (the sample is recorded:true).
    expect(o.recorded).toBe(true);
    expect(o.retryToken).toBeNull();
    expect(o.gamification).not.toBeNull();
    expect(typeof o.gamification?.xp).toBe("number");
  });

  it("PlacementResult totals the CANONICAL question count", () => {
    const p = f.placementResult as PlacementResult;
    expect(typeof p.conceptId).toBe("string");
    expect(typeof p.domain).toBe("string");
    expect(typeof p.title).toBe("string");
    expect(typeof p.correctCount).toBe("number");
    expect(typeof p.total).toBe("number");
    expect(p.total).toBe(5);
  });

  it("DailySession populates interleavedSet", () => {
    const s = f.dailySession as DailySession;
    expect(Array.isArray(s.conceptsNew)).toBe(true);
    expect(Array.isArray(s.conceptsReview)).toBe(true);
    expect(Array.isArray(s.interleavedSet)).toBe(true);
    expect(s.interleavedSet.length).toBeGreaterThan(0);
    expect(typeof s.estimatedMinutes).toBe("number");
  });

  it("DailyProgress matches", () => {
    const d = f.dailyProgress as DailyProgress;
    expect(typeof d.minutesToday).toBe("number");
    expect(typeof d.goalMinutes).toBe("number");
  });

  it("AppSettings matches", () => {
    const a = f.appSettings as AppSettings;
    expect([15, 30, 45, 60]).toContain(a.dailyGoalMinutes);
    expect(["light", "dark", "system"]).toContain(a.theme);
    expect(typeof a.baseModel).toBe("string");
    expect(typeof a.reasoningModel).toBe("string");
    expect(typeof a.newConceptsPerSession).toBe("number");
    expect(typeof a.notificationsEnabled).toBe("boolean");
    expect(typeof a.apiKeyPresent).toBe("boolean");
  });
});
